Doc = TypeDefinition* .
TypeDefinition = Literal? ("@" Name)* NamedType .
Literal = <text> .
Name = (<name> | <text>) .
NamedType = Function | Choice | Struct | Type | Alias | Context | Aggregate .
Function = KeywordFn Name (TypeDeclaration | ("(" TypeDeclaration ("," TypeDeclaration)* ")"))? FuncTypeRet? FnStmtBlock? .
KeywordFn = ("task" | "Aufgabe") .
TypeDeclaration = QualifiedName ("[" TypeDeclaration ("," TypeDeclaration)* "]")? ("|" TypeDeclaration)? "?"? .
QualifiedName = Name ("." Name)* .
FuncTypeRet = KeywordRet (TypeDeclaration | ("(" TypeDeclaration ("," TypeDeclaration)* ")")) .
KeywordRet = "->" .
FnStmtBlock = "{" FnStmts "}" .
FnStmts = FnStmt* .
FnStmt = FnStmtIf | FnStmtBlock | FuncTypeRet | FnLitExpr .
FnStmtIf = KeywordIf FnLitExpr FnStmt (KeywordElse FnStmt)? .
KeywordIf = ("if" | "wenn") .
FnLitExpr = QualifiedName ("(" (TypeDeclaration ("," TypeDeclaration)*)? ")")? .
KeywordElse = ("else" | "sonst") .
Choice = KeywordChoice Name ("{" TypeDeclaration (("," | "or" | "oder") TypeDeclaration)+ "}")? .
KeywordChoice = ("choice" | "Auswahl") .
Struct = KeywordStruct Name ("{" Field (("," | "und") Field)* "}")? .
KeywordStruct = ("data" | "Daten") .
Field = TypeDeclaration (("als" | "as") Name)? .
Type = KeywordType Name ("=" TypeDeclaration)? .
KeywordType = ("type" | "Typ") .
Alias = KeywordAlias Name ("=" TypeDeclaration)? .
KeywordAlias = ("alias" | "Synonym") .
Context = KeywordContext Name ("{" TypeDefinition* "}")? .
KeywordContext = ("context" | "Kontext") .
Aggregate = KeywordAggregate Name ("{" TypeDefinition* "}")? .
KeywordAggregate = ("aggregate" | "Aggregat") .
